# Generated by Django 3.2.9 on 2021-11-16 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comments_likes_posts_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='short_description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
