# Generated by Django 3.2.9 on 2021-11-27 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211127_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateLastParse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastDate', models.TextField()),
            ],
        ),
    ]
