# Generated by Django 3.2.9 on 2021-11-27 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_datelastparse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporters',
            name='site',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.sites'),
        ),
        migrations.AlterField(
            model_name='reporters',
            name='user',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.users'),
        ),
    ]
