# Generated by Django 3.2.9 on 2021-12-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20211201_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='role',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
