# Generated by Django 3.2.9 on 2021-12-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='posts',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
